language: java
jdk:
  - openjdk8
branches:
  only:
    - master
    - /^server\/.*$/
install:
  - ./server2/gradlew assemble --console=plain --project-dir=server2
script:
  - ./server2/gradlew test --console=plain --project-dir=server2