
jobs:
  include:
  - stage: test
    name: "server side test"
    branches:
      only:
        - master
        - /^server\/.*$/
    language: java
    jdk: openjdk8
    install: ./server2/gradlew assemble --console=plain --project-dir=server2
    script: ./server2/gradlew test integrationTest jacocoTestReport --console=plain --project-dir=server2
    after_success: bash <(curl -s https://codecov.io/bash)
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

stages:
  - name: test