version: "3"
services:
  nginx:
    build:
      context: ./
      dockerfile: .docker/nginx.dockerfile
    depends_on:
      - django
      - react
    ports:
      - "8000:8000"
    volumes:
      - server-static:/home/junk-t/static:ro
    networks:
      - host-1
  react:
    build:
      context: ./
      dockerfile: .docker/react.dockerfile
    volumes:
      - client-src:/home/junk-t/client:nocopy # nocopy is important
    networks:
      - host-1
  django:
    build:
      context: ./
      dockerfile: .docker/django.dockerfile
    depends_on:
      - mysql
    volumes:
      - server-src:/home/junk-t/server:nocopy # nocopy is important
      - server-static:/home/junk-t/static
    networks:
      - host-1
  mysql:
    image: mysql:5.7.23
    environment:
      MYSQL_DATABASE: junktion
      MYSQL_USER: junk-t
      MYSQL_PASSWORD: junk-t-pass
      MYSQL_ROOT_PASSWORD: root-pass
    networks:
    - host-1
volumes:
  client-src:
    external: true
  server-src:
    external: true
  server-static:
networks:
  host-1:
    driver: bridge