version: "3"
services:
  nginx:
    build:
      context: ./
      dockerfile: .docker/nginx.dockerfile
    depends_on:
      - django
    ports:
      - "8000:8000"
    volumes:
      - static:/home/junk-t/static:ro
    networks:
      - host-1
  django:
    build:
      context: ./
      dockerfile: .docker/django.dockerfile
    depends_on:
      - mysql
    volumes:
      - static:/home/junk-t/static
    networks:
      - host-1
  mysql:
    image: mysql:5.7.23
    environment:
      MYSQL_DATABASE: junktion
      MYSQL_USER: junk-t
      MYSQL_PASSWORD: junk-t-pass
      MYSQL_ROOT_PASSWORD: root-pass
    networks:
    - host-1
volumes:
  static:
networks:
  host-1:
    driver: bridge