spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

security:
  oauth2:
    client:
      client-id: fooClientId
      client-secret: fooClientIdPassword

junk-t:
  admin:
    user-id: user1
    password: user1Pass
