# Generated by Django 2.1.1 on 2018-09-07 12:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='resource',
            field=models.ImageField(upload_to=api.models.image_file_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='tag',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
