# Generated by Django 2.1.1 on 2018-09-16 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180907_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
